### ISSUE TITLE
Invalid header: Does not start with Cr24

### ISSUE THREAD

**Issue by tmKamal** [tmKamal/automated-timetable-generator#1]
There is an error when loading react-dev-tools.
Error:

```
Error loading React DevTools:  Error: Invalid header: Does not start with Cr24
    at crxToZip (E:\Experiment Ground\Electron.js\SPM_Project\Time-table-app\node_modules\unzip-crx\dist\index.js:32:15)
    at E:\Experiment Ground\Electron.js\SPM_Project\Time-table-app\node_modules\unzip-crx\dist\index.js:57:32
    at callHanler (E:\Experiment Ground\Electron.js\SPM_Project\Time-table-app\node_modules\yaku\lib\yaku.js:719:16)
    at tryCatcher (E:\Experiment Ground\Electron.js\SPM_Project\Time-table-app\node_modules\yaku\lib\yaku.js:436:32)
    at E:\Experiment Ground\Electron.js\SPM_Project\Time-table-app\node_modules\yaku\lib\yaku.js:575:38
    at flush (E:\Experiment Ground\Electron.js\SPM_Project\Time-table-app\node_modules\yaku\lib\yaku.js:478:17)
    at processTicksAndRejections (internal/process/task_queues.js:76:11)

```

**Comment by dasunx** [comment]
Hello Kamal


This Error comes with older version of electron-devtools-installer

Please update your electron-devtools-installer to version 3.1.1

or pull the newest commit and run `npm install`

Thank you!

**Comment by dasunx** [comment]
Re opened the issue for your feedback

**Comment by tmKamal** [comment]
> Re opened the issue for your feedback

Yeah, It worked.  
thanks DasunX.
